# Courtesy: https://github.com/magit/magit/blob/master/.travis.yml
dist: trusty
sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25 # emacs-25 branch, built daily
  # - EMACS_VERSION=master # master branch, built daily
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
script:
  - make --no-print-directory doc EMACS=${EMACS} # Just ensure that "make doc" doesn't fail for any reason.. this is *not* used to do Org->Markdown doc conversion using Travis.
  - make --no-print-directory test EMACS=${EMACS}
  - make --no-print-directory vcheck EMACS=${EMACS}
notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
    on_failure: always # The default.
